name: Docker Image CI

env:
  SPRING_PROFILES_ACTIVE: test
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  SPRING_FLYWAY_URL: ${{ secrets.SPRING_FLYWAY_URL }}
  SPRING_FLYWAY_USER: ${{ secrets.SPRING_FLYWAY_USER }}
  SPRING_FLYWAY_PASSWORD: ${{ secrets.SPRING_FLYWAY_PASSWORD }}
  JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag servicelink-backend:$(date +%s)
